name: Hoyolab Auto Daily

on:
  workflow_dispatch:  # permite rodar manualmente pelo botão "Run workflow"
  schedule:
    - cron: "30 16 * * *" # 13:30 no Brasil (UTC-3) → 16:30 UTC

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Hoyolab Check-in
        uses: sglkc/hoyolab-auto-daily@master
        with:
          cookie: ${{ secrets.COOKIE }}
          games: ${{ vars.GAMES }}
          account-description: "Conta Natan"
